# Generated by Django 4.1.7 on 2023-04-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('a', 'Option A'), ('b', 'Option B')], max_length=1)),
            ],
        ),
    ]
