# Generated by Django 4.1.7 on 2023-04-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='payment_method',
            field=models.CharField(choices=[('bkash', 'Bkash'), ('nagad', 'Nagad')], max_length=10),
        ),
    ]
