# Generated by Django 4.1.7 on 2023-04-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_deposit_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='status',
            field=models.CharField(blank=True, choices=[('Complete', 'Completed'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='trx_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bkash', 'Bkash'), ('nagad', 'Nagad')], max_length=10, null=True),
        ),
    ]
