# Generated by Django 4.1.7 on 2023-04-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_withdraw_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='trx_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
