# Generated by Django 4.1.7 on 2023-04-16 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_withdraw_trx_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0))),
                ('daily_task', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0))),
                ('daily_income', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0))),
                ('refer_bonus', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0))),
                ('plan_validity', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0))),
            ],
        ),
    ]
