# Generated by Django 4.1.7 on 2023-04-17 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_utilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilities',
            name='joining_bonus',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='utilities',
            name='n_text',
            field=models.TextField(default='সম্মানিত গ্রাহক আপনাদের অবগতির জন্য জানানো যাচ্ছে যে... ', max_length=5000, null=True),
        ),
    ]
