# Generated by Django 4.1.7 on 2023-04-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_utilities_app_link_utilities_telegram_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilities',
            name='app_link',
            field=models.URLField(default='#', null=True),
        ),
        migrations.AlterField(
            model_name='utilities',
            name='telegram_link',
            field=models.URLField(default='#', null=True),
        ),
    ]
