# Generated by Django 4.1.7 on 2023-04-19 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_utilities_app_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('work_details', models.TextField(max_length=5000)),
                ('work_link', models.URLField(blank=True, null=True)),
                ('reaward_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
