# Generated by Django 4.1.7 on 2023-04-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_completetask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completetask',
            name='status',
            field=models.CharField(blank=True, choices=[('Canceled', 'Canceled'), ('Approved', 'Approved'), ('Pending', 'Pending')], max_length=10, null=True),
        ),
    ]
