# Generated by Django 4.1.7 on 2023-04-19 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilities',
            name='free_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.packages'),
        ),
    ]
