# Generated by Django 4.1.7 on 2023-04-19 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_work_delete_freetask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completetask',
            name='package',
        ),
        migrations.AddField(
            model_name='completetask',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.work'),
        ),
    ]
