# Generated by Django 4.1.7 on 2023-04-20 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_completetask_package_completetask_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='completetask',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
