# Generated by Django 4.1.7 on 2023-04-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_completetask_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageorder',
            name='refferedby',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
