# Generated by Django 4.1.7 on 2023-04-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilities',
            name='bkash_guide',
            field=models.TextField(default='সম্মানিত গ্রাহক আপনাদের অবগতির জন্য জানানো যাচ্ছে যে... ', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='utilities',
            name='bkash_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='utilities',
            name='nagad_guide',
            field=models.TextField(default='সম্মানিত গ্রাহক আপনাদের অবগতির জন্য জানানো যাচ্ছে যে... ', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='utilities',
            name='nagad_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
